const reviews = [
  {
    id: 1,
    name: "Emily Johnson",
    country: "United States",
    role: "CEO — NovaTech Labs",
    rating: 5,
    review: "Outstanding service! Their communication, code quality, and delivery speed exceeded our expectations.",
    avatar: "EJ",
  },
  {
    id: 2,
    name: "Alexander Müller",
    country: "Germany",
    role: "Product Head — Kraft Software",
    rating: 5,
    review: "Highly professional team. They delivered a complex project with precision and amazing UI/UX.",
    avatar: "AM",
  },
  {
    id: 3,
    name: "Sophia Laurent",
    country: "France",
    role: "Founder — StudioPixel",
    rating: 4,
    review: "Creative, reliable, and extremely talented developers. Will definitely collaborate again!",
    avatar: "SL",
  },
  {
    id: 4,
    name: "James Carter",
    country: "United Kingdom",
    role: "Project Manager — BlueWave Systems",
    rating: 5,
    review: "Exceptional work! Smooth process from start to finish. Highly recommended team.",
    avatar: "JC",
  },
  {
    id: 5,
    name: "Hiroshi Tanaka",
    country: "Japan",
    role: "CTO — Nexa Robotics",
    rating: 5,
    review: "Very impressed with their attention to detail and technical expertise. Five stars without a doubt.",
    avatar: "HT",
  },

  // ⭐ New Reviews Added Below ⭐
  {
    id: 6,
    name: "Isabella Rossi",
    country: "Italy",
    role: "Marketing Director — Creativa Media",
    rating: 5,
    review: "They brought our vision to life beautifully. Excellent communication and brilliant creativity!",
    avatar: "IR",
  },
  {
    id: 7,
    name: "Carlos Mendes",
    country: "Brazil",
    role: "CEO — TechWave Solutions",
    rating: 4,
    review: "Great experience overall! Project delivered on time with strong attention to detail.",
    avatar: "CM",
  },
  {
    id: 8,
    name: "Aisha Al-Farsi",
    country: "UAE",
    role: "Founder — Digital Oasis",
    rating: 5,
    review: "Superb quality! They exceeded expectations at every step. Definitely recommended.",
    avatar: "AA",
  },
  {
    id: 9,
    name: "Liam O’Connor",
    country: "Ireland",
    role: "Tech Lead — GreenByte LLC",
    rating: 5,
    review: "Very professional and efficient team. Their problem-solving skills are exceptional.",
    avatar: "LO",
  },
  {
    id: 10,
    name: "Chen Wei",
    country: "China",
    role: "Senior Developer — SkyNet Systems",
    rating: 4,
    review: "Reliable and skilled team. Delivered solid performance and clean architecture.",
    avatar: "CW",
  },
];
